### ISSUE TITLE
Git error: bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by dave42w** [sparckles/Robyn#1027] opened 2024-11-11 18:14 UTC
### Bug Description

For some files (mostly when trying to commit multiple files) I'm getting this message (from with VSCODE and from the command line)
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/dave/.cache/pre-commit/patch1731348310-81464.
ruff.....................................................................Passed
ruff-format..............................................................Failed
- hook id: ruff-format
- files were modified by this hook

warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
  - 'mccabe' -> 'lint.mccabe'
1 file reformatted

[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
[INFO] Restored changes from /home/dave/.cache/pre-commit/patch1731348310-81464.
```

I've tried changing pyproject.toml from `[tool.ruff.mccabe]` to `[tool.ruff.lint.mccabe]` but it doesn't help.

### Steps to Reproduce

It's not entirely consistent. I can't work out why it happens for some groups of files (but not if committed singly). Latest example is after a 1 line change in authentication.py
from
```
        if "authorization" in request.headers:
``` 
to
```
        if request.headers.contains("authorization"):
``` 

### Your operating system

Linux

### Your Python version (`python --version`)

3.12

### Your Robyn version

main branch

**Comment by sansyrox** [comment] 2024-11-21 02:16
Hey @dave42w 👋 

I was unable to reproduce this error 😅 Were you able to reproduce it again? And is it only happening with Robyn?

**Comment by dave42w** [comment] 2024-11-21 11:53
I got it again last night with a commit on the static files. I eventually got it to commit without changing the code by committing only one file at a time (and it worked in one order but not the other) and by simplifying the commit message (maybe it didn't like me using _ to reference a method?)

**Comment by sansyrox** [comment] 2024-11-26 22:58
Hey @dave42w 

I found a fix here -https://stackoverflow.com/questions/55077450/linode-lish-bash-warning-setlocale-lc-all-cannot-change-locale-en-us-utf-8

Looks like it is a config issue and not a robyn issue. Can you please confirm?

**Comment by dave42w** [comment] 2024-11-26 23:39
I agree it must be environment related but it has only ever happened when using github with Robyn. I've never had it on any other github (or codeberg or gitlab) repository.

Anyway I'm trying the answers in that StackOverflow which are different to the ones I've tried before.

**Comment by dave42w** [comment] 2024-11-27 00:28
Nope got it again. Will try another option.

**Comment by sansyrox** [comment] 2024-12-08 17:49
Hey @dave42w 👋 

Is it still happening or can we close it?

**Comment by sansyrox** [comment] 2024-12-08 18:52
Alright, then!

**Closed by sansyrox** 2024-12-08 18:52 UTC
Labels: bug
