### ISSUE TITLE
Running in dev mode causes "Port is already in use" errors

### ISSUE THREAD

**Issue by laksh-21** [sparckles/Robyn#923] opened 2024-08-06 07:22 UTC
### Bug Description

Our service written with Robyn runs in a docker container. The Dockerfile is as below:
```
FROM python:3.9-slim AS build_base
ONBUILD RUN python -m pip install --upgrade pip

# Development build with source code
FROM build_base AS build_source

ONBUILD WORKDIR /app
ONBUILD COPY . .

ONBUILD RUN pip install -r requirements.txt
ONBUILD RUN printf "#!/bin/bash\ncd /app\npython3 -m robyn main.py --dev\n" > /app_startup.sh \
    && chmod +x /app_startup.sh
...
```

The docker container's logs are as follows:
```
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
dvc-internal-service  | ERROR:robyn.logger:Port 4008 is already in use. Please use a different port.
dvc-internal-service  | ERROR:robyn.logger:Invalid port number. Please enter a valid port number.
```

Even when running with a single worker and process, this issue persists.

### Steps to Reproduce

1. Start the Robyn server with `--dev` mode enabled.

### Your operating system

Linux

### Your Python version (`python --version`)

3.9

### Your Robyn version

latest

**Comment by sansyrox** [comment] 2024-08-06 22:56
Hey @laksh-21 👋 

Thanks for reporting 😄  Does the app work properly without the `--dev` flag?

**Comment by sansyrox** [comment] 2024-08-25 00:31
@laksh-21 , I will be closing this issue. Feel free to reopen if the issue is still there 😄

**Closed by sansyrox** 2024-08-25 00:31 UTC
Labels: bug
